export const MOCK_DATA = [
   {
      id: 1,
      firstName: "Gwynne",
      lastName: "Wile",
      startDate: "01/04/2013",
      department: "Engineering",
      dateOfBirth: "06/19/1983",
      streetAddress: "431 Thierer Junction",
      cityAddress: "Bradenton",
      stateNameAddress: "Florida",
      stateCodeAddress: "FL",
      codeAddress: "34282",
   },
   {
      id: 2,
      firstName: "Dudley",
      lastName: "Matson",
      startDate: "05/25/2022",
      department: "Engineering",
      dateOfBirth: "09/08/1987",
      streetAddress: "24 Rigney Parkway",
      cityAddress: "White Plains",
      stateNameAddress: "New York",
      stateCodeAddress: "NY",
      codeAddress: "10606",
   },
   {
      id: 3,
      firstName: "Basile",
      lastName: "Hills",
      startDate: "08/25/2010",
      department: "Legal",
      dateOfBirth: "08/20/1972",
      streetAddress: "281 Dexter Alley",
      cityAddress: "Decatur",
      stateNameAddress: "Georgia",
      stateCodeAddress: "GA",
      codeAddress: "30089",
   },
   {
      id: 4,
      firstName: "Glory",
      lastName: "Giacomasso",
      startDate: "06/12/2014",
      department: "Accounting",
      dateOfBirth: "09/22/1971",
      streetAddress: "5122 La Follette Lane",
      cityAddress: "South Bend",
      stateNameAddress: "Indiana",
      stateCodeAddress: "IN",
      codeAddress: "46620",
   },
   {
      id: 5,
      firstName: "Lilias",
      lastName: "Worthy",
      startDate: "02/14/2018",
      department: "Services",
      dateOfBirth: "07/29/1974",
      streetAddress: "22042 Jay Road",
      cityAddress: "Philadelphia",
      stateNameAddress: "Pennsylvania",
      stateCodeAddress: "PA",
      codeAddress: "19093",
   },
   {
      id: 6,
      firstName: "Brendon",
      lastName: "Soanes",
      startDate: "04/08/2017",
      department: "Accounting",
      dateOfBirth: "02/22/1962",
      streetAddress: "86740 Lillian Hill",
      cityAddress: "Springfield",
      stateNameAddress: "Massachusetts",
      stateCodeAddress: "MA",
      codeAddress: "01105",
   },
   {
      id: 7,
      firstName: "Maximo",
      lastName: "Matsell",
      startDate: "05/15/2011",
      department: "Engineering",
      dateOfBirth: "04/09/1987",
      streetAddress: "603 Buhler Parkway",
      cityAddress: "Seattle",
      stateNameAddress: "Washington",
      stateCodeAddress: "WA",
      codeAddress: "20436",
   },
   {
      id: 8,
      firstName: "Adrienne",
      lastName: "Pughsley",
      startDate: "06/21/2016",
      department: "Accounting",
      dateOfBirth: "04/30/1966",
      streetAddress: "77 Laurel Parkway",
      cityAddress: "San Antonio",
      stateNameAddress: "Texas",
      stateCodeAddress: "TX",
      codeAddress: "78240",
   },
   {
      id: 9,
      firstName: "Jobyna",
      lastName: "Fidler",
      startDate: "07/26/2014",
      department: "Marketing",
      dateOfBirth: "06/12/1961",
      streetAddress: "91 Oak Valley Junction",
      cityAddress: "Port Charlotte",
      stateNameAddress: "Florida",
      stateCodeAddress: "FL",
      codeAddress: "33954",
   },
   {
      id: 10,
      firstName: "Kit",
      lastName: "Tireman",
      startDate: "01/04/2014",
      department: "Human Resources",
      dateOfBirth: "11/24/1997",
      streetAddress: "9 Thackeray Trail",
      cityAddress: "Wichita",
      stateNameAddress: "Kansas",
      stateCodeAddress: "KS",
      codeAddress: "67230",
   },
   {
      id: 11,
      firstName: "Bibi",
      lastName: "Bubear",
      startDate: "07/29/2019",
      department: "Human Resources",
      dateOfBirth: "03/02/1987",
      streetAddress: "03371 Eggendart Place",
      cityAddress: "San Francisco",
      stateNameAddress: "California",
      stateCodeAddress: "CA",
      codeAddress: "94137",
   },
   {
      id: 12,
      firstName: "Elbertine",
      lastName: "Axworthy",
      startDate: "09/13/2013",
      department: "Accounting",
      dateOfBirth: "08/18/1975",
      streetAddress: "75590 Hanover Point",
      cityAddress: "Texarkana",
      stateNameAddress: "Texas",
      stateCodeAddress: "TX",
      codeAddress: "75507",
   },
   {
      id: 13,
      firstName: "Lion",
      lastName: "Dodamead",
      startDate: "06/12/2016",
      department: "Engineering",
      dateOfBirth: "11/06/1971",
      streetAddress: "592 Shoshone Hill",
      cityAddress: "Saint Paul",
      stateNameAddress: "Minnesota",
      stateCodeAddress: "MN",
      codeAddress: "55127",
   },
   {
      id: 14,
      firstName: "Clarie",
      lastName: "Scargle",
      startDate: "12/14/2019",
      department: "Legal",
      dateOfBirth: "05/15/1999",
      streetAddress: "7616 Ridgeview Road",
      cityAddress: "Jefferson",
      stateNameAddress: "Missouri",
      stateCodeAddress: "MO",
      codeAddress: "65110",
   },
   {
      id: 15,
      firstName: "Hurley",
      lastName: "Hellikes",
      startDate: "03/09/2019",
      department: "Accounting",
      dateOfBirth: "04/20/1977",
      streetAddress: "3 Ludington Park",
      cityAddress: "Seattle",
      stateNameAddress: "Washington",
      stateCodeAddress: "WA",
      codeAddress: "98140",
   },
   {
      id: 16,
      firstName: "Fran",
      lastName: "Casotti",
      startDate: "03/13/2019",
      department: "Human Resources",
      dateOfBirth: "04/16/1979",
      streetAddress: "92836 Hermina Parkway",
      cityAddress: "Nashville",
      stateNameAddress: "Tennessee",
      stateCodeAddress: "TN",
      codeAddress: "37210",
   },
   {
      id: 17,
      firstName: "Brittney",
      lastName: "Milmith",
      startDate: "06/07/2020",
      department: "Services",
      dateOfBirth: "10/01/1996",
      streetAddress: "4 Rieder streetAddress",
      cityAddress: "Davenport",
      stateNameAddress: "Tennessee",
      stateCodeAddress: "IA",
      codeAddress: "52804",
   },
   {
      id: 18,
      firstName: "Gaylord",
      lastName: "O'Shea",
      startDate: "07/26/2017",
      department: "Accounting",
      dateOfBirth: "05/29/1999",
      streetAddress: "9 2nd Parkway",
      cityAddress: "El Paso",
      stateNameAddress: "Texas",
      stateCodeAddress: "TX",
      codeAddress: "88525",
   },
   {
      id: 19,
      firstName: "Samaria",
      lastName: "Cranstoun",
      startDate: "01/27/2020",
      department: "Research and Development",
      dateOfBirth: "03/15/1965",
      streetAddress: "27 Parkside Pass",
      cityAddress: "Clearwater",
      stateNameAddress: "Florida",
      stateCodeAddress: "FL",
      codeAddress: "34615",
   },
   {
      id: 20,
      firstName: "Michell",
      lastName: "Duns",
      startDate: "05/29/2018",
      department: "Human Resources",
      dateOfBirth: "09/02/1979",
      streetAddress: "921 Erie Center",
      cityAddress: "San Francisco",
      stateNameAddress: "California",
      stateCodeAddress: "CA",
      codeAddress: "94164",
   },
   {
      id: 21,
      firstName: "Micky",
      lastName: "Huortic",
      startDate: "12/26/2013",
      department: "Research and Development",
      dateOfBirth: "05/13/1982",
      streetAddress: "00 Mallard Parkway",
      cityAddress: "Birmingham",
      stateNameAddress: "Alabama",
      stateCodeAddress: "AL",
      codeAddress: "35220",
   },
   {
      id: 22,
      firstName: "Sherm",
      lastName: "Barfoot",
      startDate: "07/07/2017",
      department: "Accounting",
      dateOfBirth: "06/14/1979",
      streetAddress: "0624 Bonner Point",
      cityAddress: "Indianapolis",
      stateNameAddress: "Indiana",
      stateCodeAddress: "IN",
      codeAddress: "46231",
   },
   {
      id: 23,
      firstName: "Dario",
      lastName: "Jeaycock",
      startDate: "04/06/2012",
      department: "Legal",
      dateOfBirth: "10/16/1997",
      streetAddress: "1790 Oneill Point",
      cityAddress: "Pittsburgh",
      stateNameAddress: "Pennsylvania",
      stateCodeAddress: "PA",
      codeAddress: "15215",
   },
   {
      id: 24,
      firstName: "Gary",
      lastName: "Darley",
      startDate: "04/08/2017",
      department: "Marketing",
      dateOfBirth: "02/26/1998",
      streetAddress: "60879 Scoville Crossing",
      cityAddress: "Waltham",
      stateNameAddress: "Massachusetts",
      stateCodeAddress: "MA",
      codeAddress: "02453",
   },
   {
      id: 25,
      firstName: "Toni",
      lastName: "Flye",
      startDate: "11/20/2015",
      department: "Human Resources",
      dateOfBirth: "09/04/1982",
      streetAddress: "66642 Harbort Crossing",
      cityAddress: "Seattle",
      stateNameAddress: "Washington",
      stateCodeAddress: "WA",
      codeAddress: "20078",
   },
   {
      id: 26,
      firstName: "Malachi",
      lastName: "MacAulay",
      startDate: "04/01/2020",
      department: "Research and Development",
      dateOfBirth: "11/30/1977",
      streetAddress: "514 3rd Plaza",
      cityAddress: "San Francisco",
      stateNameAddress: "California",
      stateCodeAddress: "CA",
      codeAddress: "94169",
   },
   {
      id: 27,
      firstName: "Udell",
      lastName: "Testro",
      startDate: "12/04/2021",
      department: "Product Management",
      dateOfBirth: "01/30/1992",
      streetAddress: "8861 Loeprich Court",
      cityAddress: "Bronx",
      stateNameAddress: "New York",
      stateCodeAddress: "NY",
      codeAddress: "10454",
   },
   {
      id: 28,
      firstName: "Wilhelm",
      lastName: "Matuszak",
      startDate: "02/16/2013",
      department: "Accounting",
      dateOfBirth: "04/27/2000",
      streetAddress: "5 Northwestern Park",
      cityAddress: "Oklahoma",
      stateNameAddress: "Oklahoma",
      stateCodeAddress: "OK",
      codeAddress: "73167",
   },
   {
      id: 29,
      firstName: "Janaye",
      lastName: "Tarplee",
      startDate: "04/15/2019",
      department: "Training",
      dateOfBirth: "11/24/1978",
      streetAddress: "40362 Boyd Road",
      cityAddress: "Stamford",
      stateNameAddress: "Connecticut",
      stateCodeAddress: "CT",
      codeAddress: "06912",
   },
   {
      id: 30,
      firstName: "Gradey",
      lastName: "Blasio",
      startDate: "12/06/2013",
      department: "Research and Development",
      dateOfBirth: "06/26/1983",
      streetAddress: "1 Springview Terrace",
      cityAddress: "Rochester",
      stateNameAddress: "New York",
      stateCodeAddress: "NY",
      codeAddress: "14604",
   },
];
